In [7]:
import pandas as pd
import mysql.connector

In [8]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="dbkampus"
)

In [9]:
query = "SELECT * FROM peserta_kelas"
df_mysql = pd.read_sql(query, conn)

print("Data dari MySQL:")
display(df_mysql.head())

Data dari MySQL:

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20372\1151706533.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_mysql = pd.read_sql(query, conn)

   id         nim                      nama  angkatan prodi kode_kelas
0   1  0110221344                YUDIANSYAH      2021    TI  DM20252-P
1   2  0110224003  MUHAMMAD BINTANG GUNAWAN      2024    TI  DM20252-P
2   3  0110224004  MUHAMMAD SHOFIYYURROHMAN      2024    TI  DM20252-P
3   4  0110224009              ZAINAB AZNUR      2024    TI  DM20252-P
4   5  0110224012             ARYA NURYAWAN      2024    TI  DM20252-P

In [10]:
df_mysql

    id         nim                      nama  angkatan prodi kode_kelas
0    1  0110221344                YUDIANSYAH      2021    TI  DM20252-P
1    2  0110224003  MUHAMMAD BINTANG GUNAWAN      2024    TI  DM20252-P
2    3  0110224004  MUHAMMAD SHOFIYYURROHMAN      2024    TI  DM20252-P
3    4  0110224009              ZAINAB AZNUR      2024    TI  DM20252-P
4    5  0110224012             ARYA NURYAWAN      2024    TI  DM20252-P
..  ..         ...                       ...       ...   ...        ...
91  92  0110224237            ANISA DWI ARUM      2024    TI  DM20252-S
92  93  0110224238               SYIFA NURUL      2024    TI  DM20252-S
93  94  0110224222                  AL HIJIR      2024    TI  DM20252-S
94  95  0110224225       RIFQ NUR FIKR AKMAL      2024    TI  DM20252-S
95  96  0110224232          NAUFAL ALFIHUSNI      2024    TI  DM20252-S

[96 rows x 6 columns]

In [11]:
df_mysql.describe()

              id     angkatan
count  96.000000    96.000000
mean   48.500000  2023.968750
std    27.856777     0.306186
min     1.000000  2021.000000
25%    24.750000  2024.000000
50%    48.500000  2024.000000
75%    72.250000  2024.000000
max    96.000000  2024.000000

In [12]:
df_excel = pd.read_excel('data/data_dm.xlsx')

print("Data dari Excel:")
display(df_excel.head())

Data dari Excel:

,Last name,First name,Username,ID number,Email address,Mobile phone,State,Started on,Completed,Time taken,...,Q. 6 /6.67,Q. 7 /6.67,Q. 8 /6.67,Q. 9 /6.67,Q. 10 /6.67,Q. 11 /6.67,Q. 12 /6.67,Q. 13 /6.67,Q. 14 /6.67,Q. 15 /6.67
0,Farhan Apriliansyah,Muhamad,110224069.0,110224069.0,0110224069@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:17 AM,13 April 2026 8:22 AM,5 mins 54 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
1,Farrelia,Keyla,110224228.0,110224228.0,0110224228@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:29 AM,9 mins 32 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
2,Febriyanti,Intan,110224028.0,110224028.0,0110224028@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:30 AM,9 mins 29 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
3,Al Razzak,Rafa,110224155.0,110224155.0,0110224155@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:27 AM,7 mins 3 secs,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67
4,Zahrodiniah,Silvia,110224019.0,110224019.0,0110224019@student.nurulfikri.ac.id,NaN,Finished,13 April 2026 8:20 AM,13 April 2026 8:30 AM,10 mins,...,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67,6.67

In [13]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 46 entries, 0 to 45
Data columns (total 26 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Last name      46 non-null     object
 1   First name     45 non-null     object
 2   Username       45 non-null     float64
 3   ID number      45 non-null     float64
 4   Email address  45 non-null     object
 5   Mobile phone   0 non-null      float64
 6   State          45 non-null     object
 7   Started on     45 non-null     object
 8   Completed      45 non-null     object
 9   Time taken     45 non-null     object
 10  Grade/100.00   46 non-null     float64
 11  Q. 1 /6.67     46 non-null     float64
 12  Q. 2 /6.67     46 non-null     float64
 13  Q. 3 /6.67     46 non-null     float64
 14  Q. 4 /6.67     46 non-null     float64
 15  Q. 5 /6.67     46 non-null     object
 16  Q. 6 /6.67     46 non-null     object
 17  Q. 7 /6.67     46 non-null     float64
 18  Q. 8 /6.67     46 non-null     float64
 19  Q. 9 /6.67     46 non-null     float64
 20  Q. 10 /6.67    46 non-null     object
 21  Q. 11 /6.67    46 non-null     float64
 22  Q. 12 /6.67    46 non-null     float64
 23  Q. 13 /6.67    46 non-null     object
 24  Q. 14 /6.67    46 non-null     float64
 25  Q. 15 /6.67    46 non-null     float64
dtypes: float64(15), object(11)
memory usage: 9.5+ KB

In [14]:
df_excel.describe()

,Username,ID number,Mobile phone,Grade/100.00,Q. 1 /6.67,Q. 2 /6.67,Q. 3 /6.67,Q. 4 /6.67,Q. 7 /6.67,Q. 8 /6.67,Q. 9 /6.67,Q. 11 /6.67,Q. 12 /6.67,Q. 14 /6.67,Q. 15 /6.67
count,4.500000e+01,4.500000e+01,0.0,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000,46.000000
mean,1.102241e+08,1.102241e+08,NaN,89.628913,6.373478,5.780652,6.225217,6.076957,6.076957,6.225217,6.076957,6.076957,6.225217,5.780652,5.484130
std,7.154223e+01,7.154223e+01,NaN,10.380445,1.374556,2.267364,1.663791,1.898171,1.898171,1.663791,1.898171,1.898171,1.663791,2.267364,2.550112
min,1.102240e+08,1.102240e+08,NaN,66.670000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.102240e+08,1.102240e+08,NaN,81.667500,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000
50%,1.102241e+08,1.102241e+08,NaN,93.330000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000
75%,1.102242e+08,1.102242e+08,NaN,100.000000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000
max,1.102242e+08,1.102242e+08,NaN,100.000000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000,6.670000

In [17]:
print(df_excel.columns)

Index(['Last name', 'First name', 'Username', 'ID number', 'Email address',
       'Mobile phone', 'State', 'Started on', 'Completed', 'Time taken',
       'Grade/100.00', 'Q. 1 /6.67', 'Q. 2 /6.67', 'Q. 3 /6.67', 'Q. 4 /6.67',
       'Q. 5 /6.67', 'Q. 6 /6.67', 'Q. 7 /6.67', 'Q. 8 /6.67', 'Q. 9 /6.67',
       'Q. 10 /6.67', 'Q. 11 /6.67', 'Q. 12 /6.67', 'Q. 13 /6.67',
       'Q. 14 /6.67', 'Q. 15 /6.67'],
      dtype='object')

In [18]:
df_excel = df_excel[['Last name', 'First name', 'ID number', 'Grade/100.00']]

In [19]:
print(df_mysql['nim'].head(5))
print(df_excel['ID number'].head(5))

0    0110221344
1    0110224003
2    0110224004
3    0110224009
4    0110224012
Name: nim, dtype: object
0    110224069.0
1    110224228.0
2    110224028.0
3    110224155.0
4    110224019.0
Name: ID number, dtype: float64

In [21]:
df_excel['ID number'] = df_excel['ID number'].fillna(0).astype(int).astype(str)
df_excel.head()

#tambahkan "0" di depan ID number yang kurang dari 8 digit
df_excel['ID number'] = "0" + df_excel['ID number']
df_excel.head()

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20372\2305047597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_excel['ID number'] = df_excel['ID number'].fillna(0).astype(int).astype(str)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20372\2305047597.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_excel['ID number'] = "0" + df_excel['ID number']

             Last name First name   ID number  Grade/100.00
0  Farhan Apriliansyah    Muhamad  0110224069         100.0
1             Farrelia      Keyla  0110224228         100.0
2           Febriyanti      Intan  0110224028         100.0
3            Al Razzak       Rafa  0110224155         100.0
4          Zahrodiniah     Silvia  0110224019         100.0

In [23]:
df_excel = df_excel.copy()
df_mysql = df_mysql.copy()

df_excel['ID number'] = df_excel['ID number'].astype(str)
df_mysql['nim'] = df_mysql['nim'].astype(str)

In [24]:
df_integrasi = pd.merge(df_mysql, df_excel, left_on='nim', right_on='ID number', how='inner')
df_integrasi.head()

,id,nim,nama,angkatan,prodi,kode_kelas,Last name,First name,ID number,Grade/100.00
0,2,0110224003,MUHAMMAD BINTANG GUNAWAN,2024,TI,DM20252-P,Bintang Gunawan,Muhammad,0110224003,66.67
1,3,0110224004,MUHAMMAD SHOFIYYURROHMAN,2024,TI,DM20252-P,Shofiyyurrohman,Muhammad,0110224004,73.33
2,4,0110224009,ZAINAB AZNUR,2024,TI,DM20252-P,Aznur,Zainab,0110224009,73.33
3,5,0110224012,ARYA NURYAWAN,2024,TI,DM20252-P,Nuryawan,Arya,0110224012,80.00
4,6,0110224014,AAN ADRIYANA,2024,TI,DM20252-P,Adriyana,Aan,0110224014,93.33

In [25]:
df_integrasi = df_integrasi[['id', 'nim', 'nama', 'Last name', 'First name', 'Grade/100.00']]

df_integrasi.head()

,id,nim,nama,Last name,First name,Grade/100.00
0,2,0110224003,MUHAMMAD BINTANG GUNAWAN,Bintang Gunawan,Muhammad,66.67
1,3,0110224004,MUHAMMAD SHOFIYYURROHMAN,Shofiyyurrohman,Muhammad,73.33
2,4,0110224009,ZAINAB AZNUR,Aznur,Zainab,73.33
3,5,0110224012,ARYA NURYAWAN,Nuryawan,Arya,80.00
4,6,0110224014,AAN ADRIYANA,Adriyana,Aan,93.33

In [26]:
df_integrasi.rename(columns={'Grade/100.00': 'Nilai'}, inplace=True)
df_integrasi.head()

   id         nim                      nama        Last name First name  Nilai
0   2  0110224003  MUHAMMAD BINTANG GUNAWAN  Bintang Gunawan   Muhammad  66.67
1   3  0110224004  MUHAMMAD SHOFIYYURROHMAN  Shofiyyurrohman   Muhammad  73.33
2   4  0110224009              ZAINAB AZNUR            Aznur     Zainab  73.33
3   5  0110224012             ARYA NURYAWAN         Nuryawan       Arya  80.00
4   6  0110224014              AAN ADRIYANA         Adriyana        Aan  93.33

In [27]:
set(df_mysql['nim']) - set(df_excel['ID number'])

{'0110221344',
 '0110224027',
 '0110224032',
 '0110224038',
 '0110224045',
 '0110224047',
 '0110224049',
 '0110224056',
 '0110224058',
 '0110224065',
 '0110224078',
 '0110224083',
 '0110224090',
 '0110224098',
 '0110224100',
 '0110224107',
 '0110224114',
 '0110224117',
 '0110224120',
 '0110224125',
 '0110224128',
 '0110224132',
 '0110224135',
 '0110224141',
 '0110224144',
 '0110224146',
 '0110224147',
 '0110224151',
 '0110224156',
 '0110224160',
 '0110224161',
 '0110224164',
 '0110224167',
 '0110224170',
 '0110224172',
 '0110224176',
 '0110224179',
 '0110224185',
 '0110224188',
 '0110224189',
 '0110224190',
 '0110224191',
 '0110224192',
 '0110224194',
 '0110224196',
 '0110224197',
 '0110224198',
 '0110224200',
 '0110224202',
 '0110224203',
 '0110224205',
 '0110224207',
 '0110224209',
 '0110224210',
 '0110224212',
 '0110224215',
 '0110224216',
 '0110224217',
 '0110224218',
 '0110224219',
 '0110224220',
 '0110224221',
 '0110224222',
 '0110224223',
 '0110224224',
 '0110224225',
 '0110224226',
 '0110224227',
 '0110224229',
 '0110224230',
 '0110224231',
 '0110224232',
 '0110224233',
 '0110224235',
 '0110224236',
 '0110224237',
 '0110224238'}