PRAKTIKUM 1

In [21]:
import pandas as pd
import matplotlib.pyplot as plt
from itertools import combinations

In [18]:
transactions_m = [
    {'ID TRANSAKSI':'T001','NO':'1','Items':['Laptop','Mouse','Keyboard','Headset']},
    {'ID TRANSAKSI':'T002','NO':'2','Items':['Handphone','Charger','Casing HP']},
    {'ID TRANSAKSI':'T003','NO':'3','Items':['Laptop','Mouse','Flashdisk']},
    {'ID TRANSAKSI':'T004','NO':'4','Items':['Handphone','Headset','Power Bank','Charger']},
    {'ID TRANSAKSI':'T005','NO':'5','Items':['Tablet','Keyboard','Mouse']},
    {'ID TRANSAKSI':'T006','NO':'6','Items':['Laptop','Keyboard','Mouse','Headset']},
    {'ID TRANSAKSI':'T007','NO':'7','Items':['Handphone','Casing HP','Flashdisk','Charger']},
    {'ID TRANSAKSI':'T008','NO':'8','Items':['Laptop','Mouse','Headset','Power Bank']},
    {'ID TRANSAKSI':'T009','NO':'9','Items':['Handphone','Charger','Power Bank']},
    {'ID TRANSAKSI':'T010','NO':'10','Items':['Tablet','Mouse','Headset','Flashdisk']},
]
 
df_m = pd.DataFrame(transactions_m).set_index('ID TRANSAKSI')
df_m

              NO                                       Items
ID TRANSAKSI
T001           1          [Laptop, Mouse, Keyboard, Headset]
T002           2             [Handphone, Charger, Casing HP]
T003           3                  [Laptop, Mouse, Flashdisk]
T004           4   [Handphone, Headset, Power Bank, Charger]
T005           5                   [Tablet, Keyboard, Mouse]
T006           6          [Laptop, Keyboard, Mouse, Headset]
T007           7  [Handphone, Casing HP, Flashdisk, Charger]
T008           8        [Laptop, Mouse, Headset, Power Bank]
T009           9            [Handphone, Charger, Power Bank]
T010          10         [Tablet, Mouse, Headset, Flashdisk]

PRAKTIKUM 2

In [19]:
from collections import Counter
 
all_txns_m = [row['Items'] for row in transactions_m]
n_m = len(all_txns_m)
 
all_items = [item for txn in all_txns_m for item in txn]
item_freq = Counter(all_items)
 
support_rows = []
for item, freq in sorted(item_freq.items(), key=lambda x: -x[1]):
    txn_ids = [t['ID TRANSAKSI'] for t in transactions_m if item in t['Items']]
    support_rows.append({
        'Item':      item,
        'Transaksi': ', '.join(txn_ids),
        'Frekuensi': freq,
        'Support':   round(freq / n_m, 1),
    })
 
df_item_support = pd.DataFrame(support_rows).set_index('Item')
df_item_support

                                     Transaksi  Frekuensi  Support
Item
Mouse       T001, T003, T005, T006, T008, T010          6      0.6
Headset           T001, T004, T006, T008, T010          5      0.5
Laptop                  T001, T003, T006, T008          4      0.4
Handphone               T002, T004, T007, T009          4      0.4
Charger                 T002, T004, T007, T009          4      0.4
Keyboard                      T001, T005, T006          3      0.3
Flashdisk                     T003, T007, T010          3      0.3
Power Bank                    T004, T008, T009          3      0.3
Casing HP                           T002, T007          2      0.2
Tablet                              T005, T010          2      0.2

PRAKTIKUM 3

In [20]:
pair_freq = Counter()
pair_txns = {}
 
for t in transactions_m:
    for pair in combinations(sorted(t['Items']), 2):
        pair_freq[pair] += 1
        pair_txns.setdefault(pair, []).append(t['ID TRANSAKSI'])
 
# Tampilkan 2-itemset dengan frekuensi >= 2
pair_rows = []
for pair, freq in sorted(pair_freq.items(), key=lambda x: (-x[1], x[0])):
    if freq >= 2:
        pair_rows.append({
            '2-Itemset':  '{' + ', '.join(pair) + '}',
            'Transaksi':  ', '.join(pair_txns[pair]),
            'Frekuensi':  freq,
            'Support':    round(freq / n_m, 1),
        })
 
df_pairs = pd.DataFrame(pair_rows).set_index('2-Itemset')
print(f'Jumlah 2-itemset (freq >= 2): {len(df_pairs)}')
df_pairs

Jumlah 2-itemset (freq >= 2): 14

                                      Transaksi  Frekuensi  Support
2-Itemset
{Charger, Handphone}     T002, T004, T007, T009          4      0.4
{Headset, Mouse}         T001, T006, T008, T010          4      0.4
{Laptop, Mouse}          T001, T003, T006, T008          4      0.4
{Headset, Laptop}              T001, T006, T008          3      0.3
{Keyboard, Mouse}              T001, T005, T006          3      0.3
{Casing HP, Charger}                 T002, T007          2      0.2
{Casing HP, Handphone}               T002, T007          2      0.2
{Charger, Power Bank}                T004, T009          2      0.2
{Flashdisk, Mouse}                   T003, T010          2      0.2
{Handphone, Power Bank}              T004, T009          2      0.2
{Headset, Keyboard}                  T001, T006          2      0.2
{Headset, Power Bank}                T004, T008          2      0.2
{Keyboard, Laptop}                   T001, T006          2      0.2
{Mouse, Tablet}                      T005, T010          2      0.2

PRAKTIKUM 4

In [22]:
MIN_SUPPORT    = 0.3
MIN_CONFIDENCE = 0.5
 
def sup_m(items):  return sum(1 for t in all_txns_m if set(items).issubset(set(t))) / n_m
def conf_m(a, b):  return sup_m(a + b) / sup_m(a)
def lift_m(a, b):  return conf_m(a, b) / sup_m(b)
 
questions = [
    (1,  'Support(Mouse)',                   sup_m(['Mouse']),                        'Support 1-itemset'),
    (2,  'Support(Headset)',                 sup_m(['Headset']),                      'Support 1-itemset'),
    (3,  'Support({Handphone, Charger})',     sup_m(['Handphone','Charger']),          'Support 2-itemset'),
    (4,  'Confidence(Handphone → Charger)',   conf_m(['Handphone'],['Charger']),       'Confidence'),
    (5,  'Confidence(Charger → Handphone)',   conf_m(['Charger'],['Handphone']),       'Confidence'),
    (6,  'Lift(Handphone → Charger)',         lift_m(['Handphone'],['Charger']),       'Lift'),
    (7,  'Support({Mouse, Headset})',         sup_m(['Mouse','Headset']),              'Support 2-itemset'),
    (8,  'Confidence(Mouse → Headset)',       conf_m(['Mouse'],['Headset']),           'Confidence'),
    (9,  'Confidence(Headset → Mouse)',       conf_m(['Headset'],['Mouse']),           'Confidence'),
    (10, 'Lift(Mouse → Headset)',             lift_m(['Mouse'],['Headset']),           'Lift'),
]
 
def is_valid(jenis, nilai):
    if   'Support'    in jenis: return nilai >= MIN_SUPPORT
    elif 'Confidence' in jenis: return nilai >= MIN_CONFIDENCE
    else:                       return nilai > 1
 
rows = [{
    'No': no, 'Pertanyaan': desc,
    'Hasil': round(val,4), 'Jenis': jenis,
    'Valid?': '✓ VALID' if is_valid(jenis, val) else '✗ TIDAK VALID'
} for no, desc, val, jenis in questions]
 
df_pm4 = pd.DataFrame(rows).set_index('No')
df_pm4

                         Pertanyaan   Hasil              Jenis   Valid?
No
1                    Support(Mouse)  0.6000  Support 1-itemset  ✓ VALID
2                  Support(Headset)  0.5000  Support 1-itemset  ✓ VALID
3     Support({Handphone, Charger})  0.4000  Support 2-itemset  ✓ VALID
4   Confidence(Handphone → Charger)  1.0000         Confidence  ✓ VALID
5   Confidence(Charger → Handphone)  1.0000         Confidence  ✓ VALID
6         Lift(Handphone → Charger)  2.5000               Lift  ✓ VALID
7         Support({Mouse, Headset})  0.4000  Support 2-itemset  ✓ VALID
8       Confidence(Mouse → Headset)  0.6667         Confidence  ✓ VALID
9       Confidence(Headset → Mouse)  0.8000         Confidence  ✓ VALID
10            Lift(Mouse → Headset)  1.3333               Lift  ✓ VALID